# Generated by Django 5.0.3 on 2024-03-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('organisator', 'Organisator'), ('admin', 'Admin')], default='player', max_length=11, verbose_name='User Type'),
        ),
    ]
