# Generated by Django 5.0.3 on 2024-03-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
