# Generated by Django 5.0.3 on 2024-03-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
