# Generated by Django 5.0.3 on 2024-03-30 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchregistration',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
    ]
