# Generated by Django 5.0.3 on 2024-03-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_matchregistration_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchregistration',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.playerprofile', verbose_name='Player'),
        ),
    ]
